version: "3.4"

services:
  lb-frontend-service:
    networks:
      - frontend
    container_name: lb-frontend
    image: kdboateng/lb-frontend-service:1.2.1
    ports:
      - "80:80"
    environment:
      - REACT_APP_BUFFERTIME=600000
      - REACT_APP_API_VERSION=api/v1

  lb-redis-service:
    networks:
      - backend
    container_name: lb-redis
    image: kdboateng/lb-redis-service:1.1
    ports:
      - "6379:6379"

  lb-auth-service:
    networks:
      - frontend
      - notification
      - backend
    container_name: lb-auth
    image: kdboateng/lb-auth-service:1.2.2
    environment:
      - REDIS_CACHE_PORT=6379
      - REDIS_CACHE_IP=lb-redis
      - AUTH_PORT=8081
      - JWT_ALGO=HS256
      - JWT_EXPIRES_IN=1800000
      - LB_BANK_API_PORT=8080
      - LB_NOTI_API_PORT=5500
      - LB_BANK_API_DOMAIN=http://lb-bank
      - LB_NOTI_API_DOMAIN=http://lb-notification
      - CORS_ALLOW_ORIGINS=*
    ports:
      - "8081:8081"

  lb-notification-service:
    networks:
      - notification
    container_name: lb-notification
    image: kdboateng/lb-notifications-go:1.0.0
    environment:
      - GO_ENV=prod
      - PORT=:5500
      - API_VERSION=api/v1
      - MONGO_URI=
      - DB_NAME=
      - USERS_COLLECTION=users
      - CUSTOMER_SERVICE_COLLECTION=customer_services
      - SMTP_HOST=smtp.office365.com
      - SMTP_PORT=587
      - COMPANY_EMAIL=
      - COMPANY_PASSWORD=
      - ACCT_AUTH_LINK=http://www.legacybanking.us/confirm-account
    ports:
      - "5500:5500"

  lb-bank-service:
    networks:
      - backend
    container_name: lb-bank
    image: kdboateng/lb-banking-api:1.2
    environment:
      - SPRING_DATASOURCE_URL=
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
    ports:
      - "8080:8080"

networks:
  frontend:
    external: true
  notification:
    external: true
  backend:
    external: true
