version: "3"

services:
  lb-webproxy-service:
    networks:
      - frontend
    container_name: lb-proxy
    image: kdboateng/lb-webproxy:1.0
    ports:
      - "80:80"
    links:
      - lb-frontend:lb-frontend
      - lb-auth:lb-auth
    deploy:
      replicas: 1
      restart_policy:
        max_attempts: 2

  lb-redis-cache-service:
    networks:
      - backend
    container_name: lb-redis-cache
    image: kdboateng/lb-redis-service:1.0
    ports:
      - "6379:6379"
    depends_on:
      - lb-auth
    deploy:
      replicas: 2
      restart_policy:
        max_attempts: 2

  lb-auth-service:
    networks:
      - frontend
      - notification
      - backend
    container_name: lb-auth
    image: kdboateng/lb-auth-service:1.0
    environment:
      - AUTH_PORT=8081
      - JWT_ALGO=HS256
      - JWT_EXPIRES_IN=1hr
      - LB_BANK_API_PORT=8080
      - LB_MESSENGER_API_PORT=5500
      - LB_BANK_API_DOMAIN=http://lb-bank
      - LB_MESSENGER_API_DOMAIN=http://lb-notifications
      - CORS_ALLOW_ORIGINS=*
    ports:
      - "8081:8081"
    deploy:
      replicas: 1
      restart_policy:
        max_attempts: 2

  lb-frontend-service:
    networks:
      - frontend
    container_name: lb-frontend
    image: kdboateng/lb-frontend-service:1.0
    environment:
      - LB_DOMAIN_NAME=http://lb-auth/api/v1
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        max_attempts: 2

  lb-notification-service:
    networks:
      - notification
    container_name: lb-notifications
    image: kdboateng/lb-notification-service:1.0
    environment:
      - MONGO_DB_URI=
      - CORS_ALLOW_ORIGINS=*
      - NOTI_PORT=5500
      - MAILER_SMTP_HOST=undefined
      - MAILER_SERVICE=undefined
      - MAILER_USERNAME=undefined
      - MAILER_PWD=undefined
      - ACCT_AUTH_LINK=undefined
    ports:
      - "5500:5500"
    depends_on:
      - lb-auth
    deploy:
      replicas: 1
      restart_policy:
        max_attempts: 2

  lb-bank-service:
    networks:
      - backend
    container_name: lb-bank
    image: kdboateng/lb-banking-api:1.0
    environment:
      - SPRING_DATASOURCE_URL=
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
    ports:
      - "8080:8080"
    depends_on:
      - lb-auth
    deploy:
      replicas: 1
      restart_policy:
        max_attempts: 2

networks:
  frontend:
    external: true
  notification:
    external: true
  backend:
    external: true
