version: "3"

services:
  lb-webproxy-service:
    networks:
      - frontend
    container_name: lb-proxy
    image: kdboateng/lb-webproxy:1.1
    ports:
      - "80:80"
    links:
      - lb-frontend:lb-frontend
      - lb-auth:lb-auth
    deploy:
      replicas: 1
      restart_policy:
        max_attempts: 2

  lb-redis-service:
    networks:
      - backend
    container_name: lb-redis
    image: kdboateng/lb-redis-service:1.1
    ports:
      - "6379:6379"
    depends_on:
      - lb-auth
    deploy:
      replicas: 1
      restart_policy:
        max_attempts: 2

  lb-auth-service:
    networks:
      - frontend
      - notification
      - backend
    container_name: lb-auth
    image: kdboateng/lb-auth-service:1.1
    environment:
      - REDIS_CACHE_PORT=6379
      - REDIS_CACHE_IP=lb-redis
      - AUTH_PORT=8081
      - JWT_ALGO=HS256
      - JWT_EXPIRES_IN=1800000
      - LB_BANK_API_PORT=8080
      - LB_NOTIFICATIONS_API_PORT=5500
      - LB_BANK_API_DOMAIN=http://lb-bank
      - LB_NOTIFICATIONS_API_DOMAIN=http://lb-notifications
      - CORS_ALLOW_ORIGINS=*
    ports:
      - "8081:8081"
    deploy:
      replicas: 1
      restart_policy:
        max_attempts: 2

  lb-notification-service:
    networks:
      - notification
    container_name: lb-notifications
    image: kdboateng/lb-notification-service:1.1
    environment:
      - MONGO_DB_URI=mongodb+srv://autodrive-admin-1:lamarrazorback2!@autodriveone.70icx.mongodb.net/legacyDB
      - CORS_ALLOW_ORIGINS=*
      - NOTI_PORT=5500
      - MAILER_SMTP_HOST=smtp.gmail.com
      - MAILER_SERVICE=gmail
      - MAILER_USERNAME=helpfromautodrive@gmail.com
      - MAILER_PWD=AllAmerican2!
      - ACCT_AUTH_LINK=http://localhost/authentication/confirm-account
    ports:
      - "5500:5500"
    depends_on:
      - lb-auth
    deploy:
      replicas: 1
      restart_policy:
        max_attempts: 2

  lb-bank-service:
    networks:
      - backend
    container_name: lb-bank
    image: kdboateng/lb-banking-api:1.1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database-1.cclv1bm5h6ql.us-east-2.rds.amazonaws.com:5432/legacydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=AllAmerican217!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
    ports:
      - "8080:8080"
    depends_on:
      - lb-auth
    deploy:
      replicas: 1
      restart_policy:
        max_attempts: 2

networks:
  frontend:
    external: true
  notification:
    external: true
  backend:
    external: true
